Properly target java 1.7 when building on jdk 11
New methods were added from JDK9 which make the generated bytecode break on JDK8 and lower unless
we explicitely specify our target. We need this because we want our library to run on Android too.
Without this fix you, on JDK1.8 and lower you will get the following error:

java.lang.NoSuchMethodError: No virtual method rewind()Ljava/nio/ByteBuffer; in class Ljava/nio/ByteBuffer;

See https://github.com/apache/felix/pull/114